### PR TITLE
Modified support for restart intervals according to JPEG-LS T.87 stan…

### PR DESCRIPTION
**Pull request by sptheoharis**

### CODE REVIEW

**Comment by thorfdbg** [comment]
Thanks for the pull request. Do I assume right that this fixes the required re-initialization of the JPEG LS context model at MTU boundaries?
If so, would it be possible to include your patch in the ISO distribution (JPEG reference software, ISO/IEC 10918-7) of the same software? It is the same code, just available under a more liberal (non-GPL) license that does not include a copy-left clause.

Thanks,

Thomas

**Comment by sptheoharis** [comment]
> JPEG reference software, ISO/IEC 10918-7

Hi Tomas,

Yes this fix is for re-initialization of context model in both Encoder/Decoder at MCU restart boundaries, since the standard defines that all restart intervals are independent each other and can compressed/decompressed at any order (and in parallel to enhance coding performance).

The JPEG.org suggests the https://github.com/thorfdbg/libjpeg (in https://jpeg.org/jpegls/software.html) as a JPEG-LS S/W and this link we also suggest to our customers as a third party JPEG-LS decoder S/W.
Since I am not familiar, could you please let me know where can I include this patch to the JPEG reference software, ISO/IEC 10918-7 ?

Thanks,
Spyros

**Comment by thorfdbg** [comment]
Spyros,
> Yes this fix is for re-initialization of context model in both 
> Encoder/Decoder at MCU restart boundaries, since the standard defines 
> that all restart intervals are independent each other and can 
> compressed/decompressed at any order (and in parallel to enhance coding 
> performance).
> 
> The JPEG.org suggests the https://github.com/thorfdbg/libjpeg 
> <https://github.com/thorfdbg/libjpeg> (in 
> https://jpeg.org/jpegls/software.html 
> <https://jpeg.org/jpegls/software.html>) as a JPEG-LS S/W and this link 
> we also suggest to our customers as a third party JPEG-LS decoder S/W.
> Since I am not familiar, could you please let me know where can I 
> include this patch to the JPEG reference software, ISO/IEC 10918-7 ?

The reference software is not publically maintained, though we (WG1 aka 
JPEG) are preparing a new release, probably appearing in two weeks. It 
is based on the same code base, thus the fix would be rather immediate.

In any case, since the ref-software is non-GPL, and this is a license 
change, I would like to ask you for permission to include your patch 
there. I'll prepare the necessary updates on the ref-software then from 
the public github code.

The difference between them is really only the license.

Greetings,
	Thomas

**Comment by sptheoharis** [comment]
> 
> Spyros,
> Yes this fix is for re-initialization of context model in both Encoder/Decoder at MCU restart boundaries, since the standard defines that all restart intervals are independent each other and can compressed/decompressed at any order (and in parallel to enhance coding performance). The JPEG.org suggests the https://github.com/thorfdbg/libjpeg <https://github.com/thorfdbg/libjpeg> (in https://jpeg.org/jpegls/software.html <https://jpeg.org/jpegls/software.html>) as a JPEG-LS S/W and this link we also suggest to our customers as a third party JPEG-LS decoder S/W. Since I am not familiar, could you please let me know where can I include this patch to the JPEG reference software, ISO/IEC 10918-7 ?
> The reference software is not publically maintained, though we (WG1 aka JPEG) are preparing a new release, probably appearing in two weeks. It is based on the same code base, thus the fix would be rather immediate. In any case, since the ref-software is non-GPL, and this is a license change, I would like to ask you for permission to include your patch there. I'll prepare the necessary updates on the ref-software then from the public github code. The difference between them is really only the license. Greetings, Thomas

Please feel free to to include this patch in the upcoming WG1 next release.

Regards,
Spyros

**Pull request closed without merging**
